/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface JobEscrowInterface extends Interface {
    getFunction(nameOrSignature: "acceptJob" | "burnPercent" | "createJob" | "finalize" | "finalizeValidation" | "fundJob" | "jobCounter" | "jobs" | "owner" | "stakeAsValidator" | "submitWork" | "token" | "treasury" | "treasuryPercent" | "validations" | "validatorCoinbaseReward" | "validatorRewardPercent" | "validatorStake" | "vote" | "workerCoinbaseReward"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CoinbaseRewardMinted" | "JobAccepted" | "JobCreated" | "JobDisputed" | "JobFinalized" | "JobFunded" | "JobVerified" | "VoteCast" | "WorkSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptJob', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'burnPercent', values?: undefined): string;
encodeFunctionData(functionFragment: 'createJob', values: [BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalize', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeValidation', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundJob', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'jobCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'jobs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'stakeAsValidator', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitWork', values: [BigNumberish, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasuryPercent', values?: undefined): string;
encodeFunctionData(functionFragment: 'validations', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validatorCoinbaseReward', values?: undefined): string;
encodeFunctionData(functionFragment: 'validatorRewardPercent', values?: undefined): string;
encodeFunctionData(functionFragment: 'validatorStake', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'workerCoinbaseReward', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'acceptJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnPercent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeValidation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jobCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jobs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeAsValidator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryPercent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatorCoinbaseReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatorRewardPercent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatorStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'workerCoinbaseReward', data: BytesLike): Result;
  }

  
    export namespace CoinbaseRewardMintedEvent {
      export type InputTuple = [jobId: BigNumberish, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [jobId: bigint, recipient: string, amount: bigint];
      export interface OutputObject {jobId: bigint, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobAcceptedEvent {
      export type InputTuple = [jobId: BigNumberish, worker: AddressLike];
      export type OutputTuple = [jobId: bigint, worker: string];
      export interface OutputObject {jobId: bigint, worker: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobCreatedEvent {
      export type InputTuple = [jobId: BigNumberish, requester: AddressLike];
      export type OutputTuple = [jobId: bigint, requester: string];
      export interface OutputObject {jobId: bigint, requester: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobDisputedEvent {
      export type InputTuple = [jobId: BigNumberish];
      export type OutputTuple = [jobId: bigint];
      export interface OutputObject {jobId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobFinalizedEvent {
      export type InputTuple = [jobId: BigNumberish];
      export type OutputTuple = [jobId: bigint];
      export interface OutputObject {jobId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobFundedEvent {
      export type InputTuple = [jobId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [jobId: bigint, amount: bigint];
      export interface OutputObject {jobId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobVerifiedEvent {
      export type InputTuple = [jobId: BigNumberish];
      export type OutputTuple = [jobId: bigint];
      export interface OutputObject {jobId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [jobId: BigNumberish, validator: AddressLike, choice: boolean];
      export type OutputTuple = [jobId: bigint, validator: string, choice: boolean];
      export interface OutputObject {jobId: bigint, validator: string, choice: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkSubmittedEvent {
      export type InputTuple = [jobId: BigNumberish, cid: string];
      export type OutputTuple = [jobId: bigint, cid: string];
      export interface OutputObject {jobId: bigint, cid: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface JobEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): JobEscrow;
    waitForDeployment(): Promise<this>;

    interface: JobEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptJob: TypedContractMethod<
      [jobId: BigNumberish, stakeAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    burnPercent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createJob: TypedContractMethod<
      [usdPrice: BigNumberish, requesterPubKey: AddressLike, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    finalize: TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    finalizeValidation: TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundJob: TypedContractMethod<
      [jobId: BigNumberish, tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    jobCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    jobs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, string, string, string, bigint, bigint, bigint, bigint] & {requester: string, worker: string, usdPrice: bigint, tokenAmount: bigint, resultHash: string, resultCID: string, requesterPubKey: string, stakeAmount: bigint, state: bigint, createdAt: bigint, deadline: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    stakeAsValidator: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitWork: TypedContractMethod<
      [jobId: BigNumberish, resultHash: BytesLike, resultCID: string, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    treasuryPercent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    validations: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint] & {yesVotes: bigint, noVotes: bigint }],
      'view'
    >
    

    
    validatorCoinbaseReward: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    validatorRewardPercent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    validatorStake: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [jobId: BigNumberish, isValid: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    workerCoinbaseReward: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptJob'): TypedContractMethod<
      [jobId: BigNumberish, stakeAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burnPercent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createJob'): TypedContractMethod<
      [usdPrice: BigNumberish, requesterPubKey: AddressLike, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalize'): TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeValidation'): TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundJob'): TypedContractMethod<
      [jobId: BigNumberish, tokenAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'jobCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'jobs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, string, string, string, bigint, bigint, bigint, bigint] & {requester: string, worker: string, usdPrice: bigint, tokenAmount: bigint, resultHash: string, resultCID: string, requesterPubKey: string, stakeAmount: bigint, state: bigint, createdAt: bigint, deadline: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stakeAsValidator'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitWork'): TypedContractMethod<
      [jobId: BigNumberish, resultHash: BytesLike, resultCID: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'treasuryPercent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'validations'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint] & {yesVotes: bigint, noVotes: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'validatorCoinbaseReward'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'validatorRewardPercent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'validatorStake'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [jobId: BigNumberish, isValid: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'workerCoinbaseReward'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'CoinbaseRewardMinted'): TypedContractEvent<CoinbaseRewardMintedEvent.InputTuple, CoinbaseRewardMintedEvent.OutputTuple, CoinbaseRewardMintedEvent.OutputObject>;
getEvent(key: 'JobAccepted'): TypedContractEvent<JobAcceptedEvent.InputTuple, JobAcceptedEvent.OutputTuple, JobAcceptedEvent.OutputObject>;
getEvent(key: 'JobCreated'): TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
getEvent(key: 'JobDisputed'): TypedContractEvent<JobDisputedEvent.InputTuple, JobDisputedEvent.OutputTuple, JobDisputedEvent.OutputObject>;
getEvent(key: 'JobFinalized'): TypedContractEvent<JobFinalizedEvent.InputTuple, JobFinalizedEvent.OutputTuple, JobFinalizedEvent.OutputObject>;
getEvent(key: 'JobFunded'): TypedContractEvent<JobFundedEvent.InputTuple, JobFundedEvent.OutputTuple, JobFundedEvent.OutputObject>;
getEvent(key: 'JobVerified'): TypedContractEvent<JobVerifiedEvent.InputTuple, JobVerifiedEvent.OutputTuple, JobVerifiedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
getEvent(key: 'WorkSubmitted'): TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;

    filters: {
      
      'CoinbaseRewardMinted(uint256,address,uint256)': TypedContractEvent<CoinbaseRewardMintedEvent.InputTuple, CoinbaseRewardMintedEvent.OutputTuple, CoinbaseRewardMintedEvent.OutputObject>;
      CoinbaseRewardMinted: TypedContractEvent<CoinbaseRewardMintedEvent.InputTuple, CoinbaseRewardMintedEvent.OutputTuple, CoinbaseRewardMintedEvent.OutputObject>;
    

      'JobAccepted(uint256,address)': TypedContractEvent<JobAcceptedEvent.InputTuple, JobAcceptedEvent.OutputTuple, JobAcceptedEvent.OutputObject>;
      JobAccepted: TypedContractEvent<JobAcceptedEvent.InputTuple, JobAcceptedEvent.OutputTuple, JobAcceptedEvent.OutputObject>;
    

      'JobCreated(uint256,address)': TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
      JobCreated: TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
    

      'JobDisputed(uint256)': TypedContractEvent<JobDisputedEvent.InputTuple, JobDisputedEvent.OutputTuple, JobDisputedEvent.OutputObject>;
      JobDisputed: TypedContractEvent<JobDisputedEvent.InputTuple, JobDisputedEvent.OutputTuple, JobDisputedEvent.OutputObject>;
    

      'JobFinalized(uint256)': TypedContractEvent<JobFinalizedEvent.InputTuple, JobFinalizedEvent.OutputTuple, JobFinalizedEvent.OutputObject>;
      JobFinalized: TypedContractEvent<JobFinalizedEvent.InputTuple, JobFinalizedEvent.OutputTuple, JobFinalizedEvent.OutputObject>;
    

      'JobFunded(uint256,uint256)': TypedContractEvent<JobFundedEvent.InputTuple, JobFundedEvent.OutputTuple, JobFundedEvent.OutputObject>;
      JobFunded: TypedContractEvent<JobFundedEvent.InputTuple, JobFundedEvent.OutputTuple, JobFundedEvent.OutputObject>;
    

      'JobVerified(uint256)': TypedContractEvent<JobVerifiedEvent.InputTuple, JobVerifiedEvent.OutputTuple, JobVerifiedEvent.OutputObject>;
      JobVerified: TypedContractEvent<JobVerifiedEvent.InputTuple, JobVerifiedEvent.OutputTuple, JobVerifiedEvent.OutputObject>;
    

      'VoteCast(uint256,address,bool)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    

      'WorkSubmitted(uint256,string)': TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
      WorkSubmitted: TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
    
    };
  }